---
title: "Assignment3"
output: html_document
---
# _Name:_Shefali Baweja
# _Student ID:_920925812

## Exercise 1: Use sum() to determine the sum of numbers from 2000 to 20000. Provide your code and the actual sum in your answer.
```
sum(2000:20000)
```

## Exercise 2: In one or two sentences, describe what the above code snippet did.
Assigns certain values to the variables a through d.

## Exercise 3: Add the contents of a and b together and place the results in a new object. Examine the result. Include your code. Try using both sum() and + ; do you get different results? If so, why?
```
a <- 5
b <- 2:20
sum(a,b)
```
output: 214 (5 plus adding all values of 2 through 20 together)
versus
```
a + b
```
output: sequence 2 through 20, with 5 added to each number
This is because the sum() command treats each number of the sequence as separate comma separated numbers. 

## Exercise 4: What is the sum of the 5th through 10th element of object b? Provide your code and the sum.
```
sum(b[5:10])
```
output: 51

## Exercise 5: What is the sum of the 3rd, 8th, and 10th element of b?
```
sum(b[c(3,8,10)])
```
Output: 24

## Exercise 6: When extracting from a 2-dimensional object, which number specifies rows and which specifies columns? What does m[3,] do? How can you extract the 3rd, 4th and 5th columns of m together as one object?
The first number is rows and the second is columns. m[3,] will select the 3rd row but doesn't specify column, so all columns are selected. You can extract columns 3 through 5 using m[,3:5].

## Exercise 7: What does the cbind command do? How about rbind? Create a new object ?n? where the first row is a new row of numbers (your choice) and the following rows are the rows from matrix m. Optional: do the same but reverse the order of the rows from matrix m.
cbind alters the matrix by adding another column with the values assigned after the comma. rbind does the same but adds another row. 
```
n <- rbind(5:9,m)
```
adds a row at the top of the matrix with values 5 through 9. 

## Exercise 8:Copy or move your Swirl Notes into the repo, add and commit them.Enter the file name(s) where prompted
